<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>1.0.0</Version>
    <Authors>HA-ActiveUserForWindows contributors</Authors>
    <Product>HA Active User for Windows</Product>
    <RepositoryUrl>https://github.com/stephenmann/HA-ActiveUserForWindows</RepositoryUrl>
  </PropertyGroup>

</Project>
